export default {
    name: 'shipEngine',
    title: 'ShipEngine Integration',
    type: 'document',
    fields: [
      {
        name: 'order',
        title: 'Order',
        type: 'reference',
        to: [{ type: 'order' }],
       
      },
      {
        name: 'shipmentId',
        title: 'Shipment ID',
        type: 'string',
        description: 'Unique ID for the shipment generated by ShipEngine.',
        
      },
      {
        name: 'trackingNumber',
        title: 'Tracking Number',
        type: 'string',
        description: 'Tracking number for the shipment.',
      
      },
      {
        name: 'carrier',
        title: 'Carrier',
        type: 'string',
        description: 'Shipping carrier used (e.g., FedEx, UPS, USPS).',
     
      },
      {
        name: 'status',
        title: 'Shipment Status',
        type: 'string',
        options: {
          list: [
            { title: 'Label Created', value: 'labelCreated' },
            { title: 'In Transit', value: 'inTransit' },
            { title: 'Delivered', value: 'delivered' },
            { title: 'Exception', value: 'exception' },
          ],
        },
       
      },
      {
        name: 'rate',
        title: 'Shipping Rate',
        type: 'number',
        description: 'Cost of shipping for the order.',
    
      },
      {
        name: 'estimatedDeliveryDate',
        title: 'Estimated Delivery Date',
        type: 'datetime',
        description: 'Estimated delivery date provided by the carrier.',
        options: {
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm',
          calendarTodayLabel: 'Today',
        },
      },
      {
        name: 'labelUrl',
        title: 'Label URL',
        type: 'url',
        description: 'URL to download the shipping label.',
   
      },
      {
        name: 'lastUpdated',
        title: 'Last Updated At',
        type: 'datetime',
        description: 'The last time the shipment data was updated.',
   
      },
    ],
  };
  